n=int(input("enter the  1 number"))
m=int(input("enter the  2 number"))
add=(m+n)
sub=(n-m)
div=(n/m)
mul=(n*m)
print("addition is",add)
print("subtraction is",sub)
print("division is",div)
print("multiplication is",mul)